# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  # users:
  #   build:
  #     context: .
  #     dockerfile: ./apps/users/Dockerfile
  #     target: development
  #   command: npm run start:dev users
  #   env_file:
  #     - ./apps/users/.env
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - 3000:3000

  # emails:
  #   build:
  #     context: .
  #     dockerfile: ./apps/emails/Dockerfile
  #     target: development
  #   command: npm run start:dev emails
  #   env_file:
  #     - ./apps/emails/.env
  #   depends_on:
  #     - mongodb-primary
  #     - mongodb-secondary
  #     - mongodb-primary
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - 3001:3001

  db:
    image: postgres:16
    container_name: eda_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7
    ports:
      - 6379:6379

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    depends_on:
      - redis

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: main
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodbdata:/data/db
      - ./.docker/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017


  #region Kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: eda_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: eda_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"  # Adding external port for host access
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: eda_kafka_ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  #endregion

  # mongodb-primary:
  #   image: docker.io/bitnami/mongodb:5.0
  #   environment:
  #     - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
  #     - MONGODB_REPLICA_SET_MODE=primary
  #     - MONGODB_ROOT_PASSWORD=password123
  #     - MONGODB_REPLICA_SET_KEY=replicasetkey123
  #   volumes:
  #     - 'mongodb_master_data:/bitnami/mongodb'
  #   ports:
  #     - '27017:27017'

  # mongodb-secondary:
  #   image: docker.io/bitnami/mongodb:5.0
  #   depends_on:
  #     - mongodb-primary
  #   environment:
  #     - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
  #     - MONGODB_REPLICA_SET_MODE=secondary
  #     - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
  #     - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
  #     - MONGODB_REPLICA_SET_KEY=replicasetkey123

  # mongodb-arbiter:
  #   image: docker.io/bitnami/mongodb:5.0
  #   depends_on:
  #     - mongodb-primary
  #   environment:
  #     - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
  #     - MONGODB_REPLICA_SET_MODE=arbiter
  #     - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
  #     - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
  #     - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodbdata:
    driver: local
  postgres_data:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
